# Generated by Django 5.0.7 on 2024-07-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='rates_count',
            field=models.IntegerField(default=0),
        ),
    ]
